export const FRASES_STATUS = [
  "Recebendo a música...",
  "Analisando o arquivo...",
  "Preparando a separação...",
  "Analisando o espectro sonoro...",
  "Mapeando as frequências...",
  "Identificando os elementos da música...",
  "Analisando as diferentes camadas...",
  "Procurando os vocais...",
  "Detectando características vocais...",
  "Identificando a presença vocal...",
  "Localizando os principais elementos instrumentais...",
  "Separando as diferentes fontes...",
  "Isolando os elementos vocais...",
  "Trabalhando nos vocais...",
  "Refinando a faixa vocal...",
  "Limpando a separação vocal...",
  "Isolando o instrumental...",
  "Refinando a faixa instrumental...",
  "Removendo interferências...",
  "Ajustando as camadas...",
  "Fazendo os últimos ajustes...",
  "Refinando o resultado...",
  "Otimizando o áudio...",
  "Preparando as faixas finais...",
  "Quase pronto...",
  "Preparando os arquivos...",
  "Salvando o resultado..."
]